name: 'spark_demo'
version: '1.0.0'
config-version: 2

profile: 'spark_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  spark_demo:
    +materialized: table
