spark_demo:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: localhost
      port: 10000
      threads: 4
      connect_retries: 5
      connect_timeout: 60
      auth: NOSASL
